create database BelatrixTest
go

use BelatrixTest
go

create table T_MODULO(
MODULO_ID INT NOT NULL PRIMARY KEY,
MODULO_DESCRIPCION VARCHAR(200),
MODULO_URL VARCHAR(200),
MODULO_ESTADO INT,
MODULO_OBSERVACION VARCHAR(200)
)
GO

INSERT INTO T_MODULO (MODULO_ID, MODULO_DESCRIPCION, MODULO_URL, MODULO_ESTADO, MODULO_OBSERVACION)
VALUES (1, 'PORTAL', '', 1, 'Belatrix test uno')
GO

CREATE PROCEDURE [dbo].[uspObtenerModulos]    
(    
 @codModulo INT    
)    
AS    
DECLARE @V_COD_PERFIL INT    
  
SET NOCOUNT ON    

SELECT 
MODULO_ID,
MODULO_DESCRIPCION,
MODULO_URL,
MODULO_ESTADO,
MODULO_OBSERVACION
FROM 
T_MODULO
WHERE  MODULO_ID =  @codModulo  
   
SET NOCOUNT OFf    

GO


exec uspObtenerModulos 1